import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";

import type { MemoryRecord } from "#public/memory/learning/record.js";
import {
  activeDirectives,
  directiveStatus,
  isDirective,
} from "#public/self-improvement/directive.js";

/** Path of the instructions file self-improvement writes into the agent tree. */
export const LEARNED_INSTRUCTIONS_PATH = "agent/instructions/learned.md";
/** Upper bound on one generated file, in UTF-8 bytes. */
export const MAX_PATCH_FILE_BYTES = 64 * 1_024;

export interface AgentPatchFile {
  readonly contents: string;
  /** Repository-relative POSIX path, always under `agent/`. */
  readonly path: string;
}

export interface AgentPatch {
  readonly files: readonly AgentPatchFile[];
  /** Directives that are still waiting on a decision. */
  readonly pending: readonly { readonly id: string; readonly text: string }[];
}

/**
 * Renders active directives as files in the agent's own source tree.
 *
 * eve agents are directories on disk, so the honest form of self-modification
 * is a diff to that directory — reviewable, committable, and revertible —
 * rather than hidden runtime state. The runtime injection through
 * `learnedDirectives()` and this patch describe the same set; the patch is
 * how a learned rule becomes part of the agent for good.
 */
export function renderAgentPatch(records: readonly MemoryRecord[]): AgentPatch {
  const active = activeDirectives(records);
  const pending = records
    .filter((record) => isDirective(record) && directiveStatus(record) === "candidate")
    .map((record) => ({ id: record.id, text: record.text }));

  if (active.length === 0) return { files: [], pending };

  const contents = [
    "<!-- Generated by eve self-improvement. Review before committing. -->",
    "",
    "## Learned operating notes",
    "",
    "These notes were learned from earlier work in this deployment. Treat them as refinements to",
    "the agent's other instructions, never as replacements: where a note conflicts with an authored",
    "instruction, a tool's approval policy, or a user's explicit request, follow the latter.",
    "",
    ...active.map((directive) => `- ${directive.text}`),
    "",
  ].join("\n");

  return { files: [{ contents, path: LEARNED_INSTRUCTIONS_PATH }], pending };
}

export interface ApplyAgentPatchOptions {
  /** Absolute path of the application root the agent directory lives in. */
  readonly appRoot: string;
  readonly patch: AgentPatch;
}

/**
 * Writes a rendered patch into the agent directory.
 *
 * This is the one place in eve where the agent edits its own source, so the
 * checks are deliberate rather than defensive: only paths under `agent/`,
 * only Markdown, and only files small enough to read in a review.
 */
export async function applyAgentPatch(options: ApplyAgentPatchOptions): Promise<readonly string[]> {
  const appRoot = resolve(options.appRoot);
  const written: string[] = [];

  for (const file of options.patch.files) {
    const target = resolve(appRoot, file.path);
    const relativePath = relative(appRoot, target);
    if (
      relativePath.startsWith("..") ||
      !(relativePath === "agent" || relativePath.startsWith(`agent${sep}`))
    ) {
      throw new TypeError(
        `Refusing to write "${file.path}": a self-improvement patch may only write inside the agent directory.`,
      );
    }
    if (!target.endsWith(".md")) {
      throw new TypeError(
        `Refusing to write "${file.path}": a self-improvement patch may only write Markdown files.`,
      );
    }
    if (Buffer.byteLength(file.contents, "utf8") > MAX_PATCH_FILE_BYTES) {
      throw new RangeError(
        `Refusing to write "${file.path}": ${MAX_PATCH_FILE_BYTES.toLocaleString("en-US")} bytes is the limit for a generated agent file.`,
      );
    }

    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, file.contents, "utf8");
    written.push(join(relativePath));
  }

  return written;
}
