import { describe, expect, it } from "vitest";

import { createRecord, type MemoryRecord } from "#public/memory/learning/record.js";
import { withStatus } from "#public/self-improvement/directive.js";
import {
  applyAgentPatch,
  LEARNED_INSTRUCTIONS_PATH,
  MAX_PATCH_FILE_BYTES,
  renderAgentPatch,
} from "#public/self-improvement/patch.js";

const NOW = Date.UTC(2026, 8, 1);

function directive(text: string, overrides: Partial<MemoryRecord> = {}): MemoryRecord {
  return { ...createRecord({ kind: "directive", text }, NOW, text.slice(0, 8)), ...overrides };
}

describe("renderAgentPatch", () => {
  it("writes nothing while every directive is still a proposal", () => {
    const patch = renderAgentPatch([directive("Prefer the replica for reads.")]);

    expect(patch.files).toEqual([]);
    expect(patch.pending).toEqual([
      { id: expect.any(String), text: "Prefer the replica for reads." },
    ]);
  });

  it("renders active directives into the agent's instructions directory", () => {
    const patch = renderAgentPatch([
      withStatus(directive("Run the migration check before deploying."), "active"),
      withStatus(directive("An old rule."), "retired"),
      directive("Still a proposal."),
    ]);

    expect(patch.files).toHaveLength(1);
    expect(patch.files[0]?.path).toBe(LEARNED_INSTRUCTIONS_PATH);
    expect(patch.files[0]?.contents).toContain("Generated by eve self-improvement");
    expect(patch.files[0]?.contents).toContain("- Run the migration check before deploying.");
    expect(patch.files[0]?.contents).not.toContain("An old rule.");
    expect(patch.pending.map((entry) => entry.text)).toEqual(["Still a proposal."]);
  });
});

describe("applyAgentPatch", () => {
  it("refuses a path outside the agent directory", async () => {
    await expect(
      applyAgentPatch({
        appRoot: "/tmp/app",
        patch: { files: [{ contents: "x", path: "../secrets.md" }], pending: [] },
      }),
    ).rejects.toThrow(/only write inside the agent directory/);
  });

  it("refuses a file that is not Markdown", async () => {
    await expect(
      applyAgentPatch({
        appRoot: "/tmp/app",
        patch: { files: [{ contents: "x", path: "agent/tools/rm.ts" }], pending: [] },
      }),
    ).rejects.toThrow(/only write Markdown files/);
  });

  it("refuses a file too large to review", async () => {
    await expect(
      applyAgentPatch({
        appRoot: "/tmp/app",
        patch: {
          files: [
            { contents: "x".repeat(MAX_PATCH_FILE_BYTES + 1), path: LEARNED_INSTRUCTIONS_PATH },
          ],
          pending: [],
        },
      }),
    ).rejects.toThrow(/is the limit for a generated agent file/);
  });
});
